#!/usr/bin/env python3

import os
import shutil
from pathlib import Path

SOURCE = Path.home() / "Omega-Production/omega_bank"
DEST = Path.home() / "omega-financial-os"

STRUCTURE = {
    "core": [
        "ledger_engine.py",
        "transaction_processor.py",
        "account_service.py",
    ],
    "kernel": [
        "db_registry.py",
        "schema_translate.py",
        "bootstrap.py",
    ],
    "integrations": [
        "stripe_bridge.py",
        "webhook_ingest.py",
    ],
    "cli": [
        "omega_shell.py",
    ],
    "tests": [
        "system_test.py",
        "integrity_checks.py",
    ],
    "db": [
        "omega_ledger.db",
    ],
}

def copy_if_exists(src, dst):
    if src.exists():
        shutil.copy2(src, dst)
        print(f"[COPIED] {src} → {dst}")
    else:
        dst.write_text(f"# placeholder: {dst.name}\n")
        print(f"[CREATED PLACEHOLDER] {dst}")

def main():
    print("=== OMEGA PROJECT BUILDER START ===")

    DEST.mkdir(parents=True, exist_ok=True)

    # build structure
    for folder, files in STRUCTURE.items():
        folder_path = DEST / folder
        folder_path.mkdir(parents=True, exist_ok=True)

        for f in files:
            src_file = SOURCE / f
            dst_file = folder_path / f

            copy_if_exists(src_file, dst_file)

    # README
    readme = DEST / "README.md"
    readme.write_text("""
# Omega Financial OS

Event-driven financial operating system.

## Modules
- Core ledger engine
- Transaction processor
- Account system
- Stripe integration layer
- CLI shell interface

## Status
Initial scaffold generated by Omega Project Builder.
""".strip())

    print("\n=== BUILD COMPLETE ===")
    print(f"Project created at: {DEST}")

if __name__ == "__main__":
    main()
