-- PREVENT DIRECT LEDGER MODIFICATION OUTSIDE COORDINATOR

CREATE OR REPLACE FUNCTION block_direct_ledger_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'LEDGER IS WRITE-LOCKED. USE COORDINATOR ONLY.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ledger_protect ON ledger_entries;

CREATE TRIGGER ledger_protect
BEFORE UPDATE OR DELETE ON ledger_entries
FOR EACH ROW
EXECUTE FUNCTION block_direct_ledger_mutation();
