-- OMEGA FINANCIAL SCHEMA CONTRACT (SOURCE OF TRUTH)

-- INVARIANT FAILURES
-- DO NOT MODIFY COLUMN NAMES WITHOUT MIGRATION
CREATE TABLE IF NOT EXISTS invariant_failures (
    id UUID PRIMARY KEY,
    type TEXT,
    status TEXT,
    created_at TIMESTAMP,
    message TEXT
);
