class SettlementState:
    RECEIVED = "RECEIVED"
    AUTHORIZED = "AUTHORIZED"
    HELD = "HELD"
    PENDING = "PENDING_SETTLEMENT"
    SETTLING = "SETTLING"
    SETTLED = "SETTLED"
    FAILED = "FAILED"
