class TransactionState:
    REQUESTED = "REQUESTED"
    AUTHORIZED = "AUTHORIZED"
    HELD = "HELD"
    PENDING_SETTLEMENT = "PENDING_SETTLEMENT"
    SETTLING = "SETTLING"
    SETTLED = "SETTLED"
    FAILED = "FAILED"
